services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:trRNvYdxn+A2zYRAJ+sEqdkv5oh6VPFCb8hw2yHzGUc=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-app.onrender.com

      # Database (gantilah sesuai konfigurasi database Render kamu)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sparking
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: your-db-password

      # Mail config
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: sparkingiotai@gmail.com
      - key: MAIL_PASSWORD
        value: fgizqbqcfqfobwjw
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: sparkingiotai@gmail.com
      - key: MAIL_FROM_NAME
        value: "SPARKING"

      # Session
      - key: SESSION_DRIVER
        value: database

      # Cache (opsional, jika kamu pakai database untuk cache)
      - key: CACHE_STORE
        value: database
